// Code generated by conversion-gen. DO NOT EDIT.

package conversion

import (
	v1alpha1 "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ServiceSetFields contains platform-managed fields injected during UnprojectX conversions
type ServiceSetFields struct {
	// AccountID is service-set (platform-managed, hidden from API)
	AccountID string `json:"accountId"`
	// AllowedUnsafeSysctls is service-set (platform-managed, hidden from API)
	AllowedUnsafeSysctls []string `json:"allowedUnsafeSysctls"`
	// ApiServer is service-set (platform-managed, hidden from API)
	ApiServer *v1alpha1.APIServerNetworkConfiguration `json:"apiServer"`
	// Authentication is service-set (platform-managed, hidden from API)
	Authentication *v1alpha1.ClusterAuthentication `json:"authentication"`
	// CpuManagerPolicy is service-set (platform-managed, hidden from API)
	CpuManagerPolicy *string `json:"cpuManagerPolicy"`
	// CpuManagerPolicyOptions is service-set (platform-managed, hidden from API)
	CpuManagerPolicyOptions map[string]string `json:"cpuManagerPolicyOptions"`
	// CpuManagerReconcilePeriod is service-set (platform-managed, hidden from API)
	CpuManagerReconcilePeriod *metav1.Duration `json:"cpuManagerReconcilePeriod"`
	// CreatorARN is service-set (platform-managed, hidden from API)
	CreatorARN string `json:"creatorARN"`
	// EvictionHard is service-set (platform-managed, hidden from API)
	EvictionHard map[string]string `json:"evictionHard"`
	// EvictionSoft is service-set (platform-managed, hidden from API)
	EvictionSoft map[string]string `json:"evictionSoft"`
	// EvictionSoftGracePeriod is service-set (platform-managed, hidden from API)
	EvictionSoftGracePeriod map[string]string `json:"evictionSoftGracePeriod"`
	// Extensions is service-set (platform-managed, hidden from API)
	Extensions []string `json:"extensions"`
	// FeatureGate is service-set (platform-managed, hidden from API)
	FeatureGate *v1alpha1.FeatureGateConfiguration `json:"featureGate"`
	// Files is service-set (platform-managed, hidden from API)
	Files []v1alpha1.FileSpec `json:"files"`
	// Image is service-set (platform-managed, hidden from API)
	Image *v1alpha1.ImageConfiguration `json:"image"`
	// Ingress is service-set (platform-managed, hidden from API)
	Ingress *v1alpha1.IngressConfiguration `json:"ingress"`
	// InternalID is service-set (platform-managed, hidden from API)
	InternalID string `json:"internalId"`
	// InternalPoolID is service-set (platform-managed, hidden from API)
	InternalPoolID string `json:"internalPoolId"`
	// KernelArguments is service-set (platform-managed, hidden from API)
	KernelArguments []string `json:"kernelArguments"`
	// KernelType is service-set (platform-managed, hidden from API)
	KernelType *string `json:"kernelType"`
	// Kubelet is service-set (platform-managed, hidden from API)
	Kubelet *v1alpha1.KubeletConfig `json:"kubelet"`
	// MachineConfig is service-set (platform-managed, hidden from API)
	MachineConfig *v1alpha1.MachineConfigSpec `json:"machineConfig"`
	// MemoryThrottlingFactor is service-set (platform-managed, hidden from API)
	MemoryThrottlingFactor *float64 `json:"memoryThrottlingFactor"`
	// Network is service-set (platform-managed, hidden from API)
	Network *v1alpha1.NetworkConfiguration `json:"network"`
	// Oauth is service-set (platform-managed, hidden from API)
	Oauth *v1alpha1.OAuthConfiguration `json:"oauth"`
	// Proxy is service-set (platform-managed, hidden from API)
	Proxy *v1alpha1.ProxyConfiguration `json:"proxy"`
	// Scheduler is service-set (platform-managed, hidden from API)
	Scheduler *v1alpha1.SchedulerConfiguration `json:"scheduler"`
	// SystemdUnits is service-set (platform-managed, hidden from API)
	SystemdUnits []v1alpha1.SystemdUnit `json:"systemdUnits"`
	// TopologyManagerPolicy is service-set (platform-managed, hidden from API)
	TopologyManagerPolicy *string `json:"topologyManagerPolicy"`
	// TopologyManagerScope is service-set (platform-managed, hidden from API)
	TopologyManagerScope *string `json:"topologyManagerScope"`
}
