ARG TARGETOS=linux
ARG TARGETARCH=amd64

FROM --platform=${TARGETOS}/${TARGETARCH} registry.access.redhat.com/ubi9/go-toolset:1.26.4-1783442369

USER root
WORKDIR /app

RUN dnf install -y git ca-certificates make bash --setopt=install_weak_deps=False && dnf clean all

RUN mkdir -p /app/test-results && chown 1001:0 /app/test-results

USER 1001

RUN go install github.com/onsi/ginkgo/v2/ginkgo@v2.28.1

COPY hyperfleet-db/go.mod hyperfleet-db/go.sum ./hyperfleet-db/
COPY hyperfleet-operator/api/go.mod hyperfleet-operator/api/go.sum ./hyperfleet-operator/api/
COPY platform-api/go.mod platform-api/go.sum ./platform-api/
RUN cd platform-api && go mod download

COPY hyperfleet-db/ ./hyperfleet-db/
COPY hyperfleet-operator/api/ ./hyperfleet-operator/api/
COPY platform-api/ ./platform-api/
COPY test/ ./test/

ENV E2E_BASE_URL=""
ENV E2E_ACCOUNT_ID=""

CMD ["ginkgo", "-vv", "--skip=Authz", "--junit-report=junit.xml", "--output-dir=/app/test-results", "./test/e2e-api"]
