/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by wire-gen. DO NOT EDIT.

package wrappers

import (
	"context"
	"errors"
	"time"

	k8serrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/rest"

	v1alpha1 "github.com/openshift-online/rosa-hyperfleet-api/hyperfleet-operator/api/v1alpha1"
	internalversion "github.com/openshift-online/rosa-hyperfleet-api/clientset/clientset/clientset/typed/v1alpha1/internalversion"
)

// ErrWatchNotSupported is returned by Watch on all resources. The Hyperfleet
// platform API does not support the Kubernetes watch stream protocol; use
// WaitUntil for polling-based synchronisation instead.
var ErrWatchNotSupported = errors.New("watch is not supported by the Hyperfleet platform API")

// ClusterInterface extends the generated interface with platform-specific methods.
type ClusterInterface interface {
	internalversion.ClusterInterface
	// WaitUntil polls until condition(obj) returns true, the resource is absent
	// (condition is called with nil), or the timeout elapses.
	WaitUntil(ctx context.Context, id string, condition func(*v1alpha1.Cluster) bool, interval, timeout time.Duration) error
}

type clusterClient struct {
	internalversion.ClusterInterface
}

func (c *clusterClient) Watch(_ context.Context, _ metav1.ListOptions) (watch.Interface, error) {
	return nil, ErrWatchNotSupported
}

func (c *clusterClient) WaitUntil(ctx context.Context, id string, condition func(*v1alpha1.Cluster) bool, interval, timeout time.Duration) error {
	ctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	poll := func() (bool, error) {
		obj, err := c.Get(ctx, id, metav1.GetOptions{})
		if err != nil {
			if k8serrors.IsNotFound(err) {
				return condition(nil), nil
			}
			return false, err
		}
		return condition(obj), nil
	}
	if done, err := poll(); err != nil || done {
		return err
	}
	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-ticker.C:
			if done, err := poll(); err != nil || done {
				return err
			}
		}
	}
}


// NodePoolInterface extends the generated interface with platform-specific methods.
type NodePoolInterface interface {
	internalversion.NodePoolInterface
	// WaitUntil polls until condition(obj) returns true, the resource is absent
	// (condition is called with nil), or the timeout elapses.
	WaitUntil(ctx context.Context, id string, condition func(*v1alpha1.NodePool) bool, interval, timeout time.Duration) error
}

type nodePoolClient struct {
	internalversion.NodePoolInterface
}

func (c *nodePoolClient) Watch(_ context.Context, _ metav1.ListOptions) (watch.Interface, error) {
	return nil, ErrWatchNotSupported
}

func (c *nodePoolClient) WaitUntil(ctx context.Context, id string, condition func(*v1alpha1.NodePool) bool, interval, timeout time.Duration) error {
	ctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	poll := func() (bool, error) {
		obj, err := c.Get(ctx, id, metav1.GetOptions{})
		if err != nil {
			if k8serrors.IsNotFound(err) {
				return condition(nil), nil
			}
			return false, err
		}
		return condition(obj), nil
	}
	if done, err := poll(); err != nil || done {
		return err
	}
	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-ticker.C:
			if done, err := poll(); err != nil || done {
				return err
			}
		}
	}
}

// V1alpha1Interface is the extended typed client for the hyperfleet.io/v1alpha1 group.
type V1alpha1Interface interface {
	RESTClient() rest.Interface
	Clusters(namespace string) ClusterInterface
	NodePools(namespace string) NodePoolInterface
}

type wrappedV1alpha1 struct {
	inner internalversion.V1alpha1Interface
}

// NewV1alpha1Client wraps the generated typed client, overriding Watch and adding WaitUntil.
func NewV1alpha1Client(inner internalversion.V1alpha1Interface) V1alpha1Interface {
	return &wrappedV1alpha1{inner: inner}
}

func (w *wrappedV1alpha1) RESTClient() rest.Interface {
	return w.inner.RESTClient()
}

func (w *wrappedV1alpha1) Clusters(namespace string) ClusterInterface {
	return &clusterClient{
		ClusterInterface: w.inner.Clusters(namespace),
	}
}

func (w *wrappedV1alpha1) NodePools(namespace string) NodePoolInterface {
	return &nodePoolClient{
		NodePoolInterface: w.inner.NodePools(namespace),
	}
}
