/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package transport

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
	"strings"
)

// FieldMapping declares a correspondence between a platform-api wire-format
// field name and a Kubernetes metadata field name.
type FieldMapping struct {
	Wire string // flat field name in the platform-api response/request body
	Meta string // field name inside the Kubernetes metadata object
}

// Adapter wraps an inner RoundTripper and rewrites platform-api wire format
// responses into the Kubernetes metadata structure expected by the generated decoder.
type Adapter struct {
	inner    http.RoundTripper
	mappings []FieldMapping
}

// NewAdapter returns an Adapter that wraps inner. Field mappings are loaded
// from defaultMappings, which is generated by wire-gen from +wire:field markers
// on the CRD types and must not be configured by callers.
func NewAdapter(inner http.RoundTripper) *Adapter {
	return &Adapter{inner: inner, mappings: defaultMappings}
}

func (a *Adapter) RoundTrip(req *http.Request) (*http.Response, error) {
	req = a.adaptRequest(req)
	req = a.adaptListQuery(req)
	resp, err := a.inner.RoundTrip(req)
	if err != nil {
		return nil, err
	}
	return a.adaptResponse(resp), nil
}

// adaptRequest transforms a Kubernetes-format request body into the platform-api
// wire format, the inverse of adaptResponse.
//
// The Kubernetes serializer produces nested metadata:
//
//	{"metadata": {"name": "...", "uid": "...", "resourceVersion": "..."}, "spec": {...}}
//
// Platform-api expects these fields flat at the top level.
// Requests without a body or without a "metadata" key are returned unchanged.
//
// For PUT and PATCH requests the last URL path segment is rewritten to the
// resource's wire "id" (UID). The generated client builds the path from
// cluster.Name (the human-readable name), but the platform API routes
// mutations by UID.
func (a *Adapter) adaptRequest(req *http.Request) *http.Request {
	if req.Body == nil {
		return req
	}

	body, err := io.ReadAll(req.Body)
	_ = req.Body.Close()
	if err != nil {
		req.Body = io.NopCloser(bytes.NewReader(body))
		return req
	}

	var raw map[string]json.RawMessage
	if err := json.Unmarshal(body, &raw); err != nil {
		req.Body = io.NopCloser(bytes.NewReader(body))
		return req
	}

	metaJSON, ok := raw["metadata"]
	if !ok {
		req.Body = io.NopCloser(bytes.NewReader(body))
		return req
	}

	var meta map[string]json.RawMessage
	if err := json.Unmarshal(metaJSON, &meta); err != nil {
		req.Body = io.NopCloser(bytes.NewReader(body))
		return req
	}

	for _, fm := range a.mappings {
		if v, ok := meta[fm.Meta]; ok {
			raw[fm.Wire] = v
		}
	}
	delete(raw, "metadata")

	// For namespaced POST requests the Kubernetes client encodes the parent
	// resource ID (e.g. clusterID) as the URL namespace segment. The platform
	// API expects it as a "cluster_id" body field instead, so inject it here
	// before the SigV4 transport strips the namespace from the URL.
	if req.Method == http.MethodPost {
		if m := namespaceRE.FindStringSubmatchIndex(req.URL.Path); m != nil {
			ns := req.URL.Path[m[2]:m[3]]
			if ns != "" {
				if _, exists := raw["cluster_id"]; !exists {
					raw["cluster_id"], _ = json.Marshal(ns)
				}
			}
		}
	}

	adapted, err := json.Marshal(raw)
	if err != nil {
		req.Body = io.NopCloser(bytes.NewReader(body))
		return req
	}

	req = req.Clone(req.Context())
	req.Body = io.NopCloser(bytes.NewReader(adapted))
	req.ContentLength = int64(len(adapted))

	if req.Method == http.MethodPut || req.Method == http.MethodPatch {
		if idJSON, ok := raw["id"]; ok {
			var id string
			if err := json.Unmarshal(idJSON, &id); err == nil && id != "" {
				if idx := strings.LastIndex(req.URL.Path, "/"); idx >= 0 {
					u := *req.URL
					u.Path = req.URL.Path[:idx+1] + id
					req.URL = &u
				}
			}
		}
	}

	return req
}

// adaptResponse transforms a platform-api wire response into the Kubernetes
// object format expected by the generated client decoder.
//
// Platform-api returns flat objects:
//
//	{"id": "...", "name": "...", "resource_version": "...", "spec": {...}, ...}
//
// The Kubernetes runtime decoder populates v1alpha1.Cluster by JSON field name,
// so it expects the cluster name in metadata.name, the UUID in metadata.uid, etc.
// Fields that have no mapping are preserved as-is (spec, status pass through).
func (a *Adapter) adaptResponse(resp *http.Response) *http.Response {
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return resp
	}

	body, err := io.ReadAll(resp.Body)
	_ = resp.Body.Close()
	if err != nil {
		resp.Body = io.NopCloser(bytes.NewReader(body))
		return resp
	}

	var raw map[string]json.RawMessage
	if err := json.Unmarshal(body, &raw); err != nil {
		resp.Body = io.NopCloser(bytes.NewReader(body))
		return resp
	}

	var adapted []byte
	if itemsJSON, ok := raw["items"]; ok {
		adapted = a.adaptList(raw, itemsJSON)
	} else if a.hasWireField(raw) {
		adapted = a.adaptItem(raw)
	} else {
		adapted = body
	}

	resp.Body = io.NopCloser(bytes.NewReader(adapted))
	resp.ContentLength = int64(len(adapted))
	return resp
}

// hasWireField reports whether any mapped wire field is present in raw,
// used to detect single-object responses.
func (a *Adapter) hasWireField(raw map[string]json.RawMessage) bool {
	for _, fm := range a.mappings {
		if _, ok := raw[fm.Wire]; ok {
			return true
		}
	}
	return false
}

// adaptList rewrites {"items": [...]} to {"items": [<adapted item>, ...]}.
func (a *Adapter) adaptList(raw map[string]json.RawMessage, itemsJSON json.RawMessage) []byte {
	var items []json.RawMessage
	if err := json.Unmarshal(itemsJSON, &items); err != nil {
		out, _ := json.Marshal(raw)
		return out
	}

	adapted := make([]json.RawMessage, len(items))
	for i, item := range items {
		var m map[string]json.RawMessage
		if err := json.Unmarshal(item, &m); err != nil {
			adapted[i] = item
			continue
		}
		adapted[i] = a.adaptItem(m)
	}

	raw["items"], _ = json.Marshal(adapted)
	out, _ := json.Marshal(raw)
	return out
}

// adaptListQuery translates the Kubernetes-style ?continue=N query parameter to
// the platform API's ?offset=N parameter for GET (list) requests.
//
// The Kubernetes generated client serializes metav1.ListOptions.Continue as the
// "continue" query parameter, which is normally a cursor token for page-safe
// continuation. The Hyperfleet platform API uses offset-based pagination instead:
// it has no cursor mechanism and accepts an integer "offset" parameter.
//
// The wrappers.ListOptions.Offset field is bridged by encoding the integer offset
// as a numeric string in ListOptions.Continue before calling the inner client.
// This method recognizes that encoding and rewrites the query parameter so the
// platform API receives the value it expects.
//
// Non-numeric "continue" values (real continuation tokens, if ever introduced)
// are passed through unchanged.
func (a *Adapter) adaptListQuery(req *http.Request) *http.Request {
	if req.Method != http.MethodGet {
		return req
	}
	q := req.URL.Query()
	cont := q.Get("continue")
	if cont == "" {
		return req
	}
	if _, err := strconv.ParseInt(cont, 10, 64); err != nil {
		return req
	}
	req = req.Clone(req.Context())
	q.Del("continue")
	q.Set("offset", cont)
	req.URL.RawQuery = q.Encode()
	return req
}

// adaptItem lifts wire-format envelope fields into metadata using the configured
// mappings. All other fields (spec, status, etc.) are preserved unchanged.
func (a *Adapter) adaptItem(m map[string]json.RawMessage) json.RawMessage {
	meta := make(map[string]json.RawMessage)

	for _, fm := range a.mappings {
		if v, ok := m[fm.Wire]; ok {
			meta[fm.Meta] = v
			delete(m, fm.Wire)
		}
	}

	if metaJSON, err := json.Marshal(meta); err == nil {
		m["metadata"] = metaJSON
	}

	out, _ := json.Marshal(m)
	return out
}
