/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// wire-gen reads +wire:field markers from Go source files and emits a
// wire_mappings_generated.go file containing a FieldMapping slice that the
// transport.Adapter uses to translate between platform-api wire format and
// Kubernetes metadata fields.
package main

import (
	"flag"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"text/template"
	"time"
)

var wireMarkerRE = regexp.MustCompile(`\+wire:field=([^,\s]+),meta=([^\s]+)`)

type fieldMapping struct {
	Wire string
	Meta string
}

const outputTmpl = `// Code generated by wire-gen. DO NOT EDIT.

package {{.Package}}

// defaultMappings maps platform-api wire-format field names to Kubernetes
// metadata field names. Generated from +wire:field markers on CRD types.
var defaultMappings = []FieldMapping{
{{- range .Mappings}}
	{Wire: "{{.Wire}}", Meta: "{{.Meta}}"},
{{- end}}
}
`

func main() {
	inputDir   := flag.String("input-dir", "", "directory of Go source files to scan for +wire:field markers")
	outputDir  := flag.String("output-dir", "", "directory to write wire_mappings_generated.go")
	outputPkg  := flag.String("output-pkg", "transport", "Go package name for the generated file")
	headerFile := flag.String("go-header-file", "", "file whose contents are prepended to the generated output")
	flag.Parse()

	if *inputDir == "" || *outputDir == "" {
		fmt.Fprintln(os.Stderr, "wire-gen: --input-dir and --output-dir are required")
		os.Exit(1)
	}

	mappings := collectMappings(*inputDir)

	header := readHeader(*headerFile)

	if err := os.MkdirAll(*outputDir, 0o755); err != nil {
		fatalf("creating output dir: %v", err)
	}

	outPath := filepath.Join(*outputDir, "wire_mappings_generated.go")
	f, err := os.Create(outPath)
	if err != nil {
		fatalf("creating %s: %v", outPath, err)
	}
	defer f.Close()

	fmt.Fprint(f, header)

	tmpl := template.Must(template.New("wire").Parse(outputTmpl))
	if err := tmpl.Execute(f, map[string]any{
		"Package":  *outputPkg,
		"Mappings": mappings,
	}); err != nil {
		fatalf("rendering template: %v", err)
	}

	fmt.Printf("wire-gen: wrote %s\n", outPath)
}

// collectMappings parses all Go source files in dir, extracts unique
// +wire:field=<wire>,meta=<meta> markers from any comment in the file, and
// returns them sorted by wire field name for deterministic output.
//
// All comment groups are scanned (not just doc comments) so that markers can
// appear in floating comment blocks — consistent with how client-gen and
// controller-gen read markers.
func collectMappings(dir string) []fieldMapping {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		fatalf("parsing %s: %v", dir, err)
	}

	seen := map[string]bool{}
	var mappings []fieldMapping

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, cg := range file.Comments {
				for _, comment := range cg.List {
					for _, m := range wireMarkerRE.FindAllStringSubmatch(comment.Text, -1) {
						key := m[1] + ":" + m[2]
						if !seen[key] {
							seen[key] = true
							mappings = append(mappings, fieldMapping{Wire: m[1], Meta: m[2]})
						}
					}
				}
			}
		}
	}

	sort.Slice(mappings, func(i, j int) bool { return mappings[i].Wire < mappings[j].Wire })
	return mappings
}

func readHeader(path string) string {
	if path == "" {
		return ""
	}
	b, err := os.ReadFile(path)
	if err != nil {
		fatalf("reading header file: %v", err)
	}
	return strings.ReplaceAll(string(b), "YEAR", strconv.Itoa(time.Now().Year()))
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "wire-gen: "+format+"\n", args...)
	os.Exit(1)
}
