// Code generated by conversion-gen. DO NOT EDIT.

package public

// Cluster is the Schema for the clusters API.
// It represents a ROSA HCP cluster whose lifecycle is managed by the hyperfleet-operator.
// metadata.Name is the human-readable cluster name; metadata.Namespace is the cluster UUID.
// The owning account is the label hyperfleet.io/account-id.
type Cluster struct {
	// +required
	Spec ClusterSpec `json:"spec"`
	// +optional
	Status ClusterStatus `json:"status,omitzero"`
}
