// Code generated by conversion-gen. DO NOT EDIT.

package public

// MachineConfigSpec specifies machine-level configuration.
type MachineConfigSpec struct {
	// +openshift:enable:FeatureGate=HyperFleetMachineConfig
	// +hyperfleet:write-mode=immutable
	AllowedKernelArguments []string `json:"allowedKernelArguments,omitempty"`
	// +k8s:openapi-gen=false
	// +hyperfleet:write-mode=service-set
	KernelArguments []string `json:"kernelArguments,omitempty"`
	// +k8s:openapi-gen=false
	// +hyperfleet:write-mode=service-set
	SystemdUnits []SystemdUnit `json:"systemdUnits,omitempty"`
	// +k8s:openapi-gen=false
	// +hyperfleet:write-mode=service-set
	Files []FileSpec `json:"files,omitempty"`
	// +hyperfleet:write-mode=immutable
	FIPS *bool `json:"fips,omitempty"`
	// +k8s:openapi-gen=false
	// +hyperfleet:write-mode=service-set
	KernelType *string `json:"kernelType,omitempty"`
	// +k8s:openapi-gen=false
	// +hyperfleet:write-mode=service-set
	Extensions []string `json:"extensions,omitempty"`
}
