// Code generated by conversion-gen. DO NOT EDIT.

package public

// ManagementCluster is the Schema for the managementclusters API.
// It represents a management cluster in the fleet.
type ManagementCluster struct {
	// +required
	Spec ManagementClusterSpec `json:"spec"`
	// +optional
	Status ManagementClusterStatus `json:"status,omitzero"`
}
