// Code generated by conversion-gen. DO NOT EDIT.

package public

// Manifest is the Schema for the manifests API.
// It deploys arbitrary Kubernetes resources to a management cluster via DynamoDB desires.
type Manifest struct {
	// +required
	Spec ManifestSpec `json:"spec"`
	// +optional
	Status ManifestStatus `json:"status,omitzero"`
}
