// Code generated by conversion-gen. DO NOT EDIT.

package public

import (
	hypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
)

// NodePoolSpecPassthrough mirrors NodePoolSpec from upstream HyperShift
type NodePoolSpecPassthrough struct {
	// platform specifies the underlying infrastructure provider for the NodePool
	// +k8s:openapi-gen=true
	// +hyperfleet:write-mode=mutable
	Platform hypershiftv1beta1.NodePoolPlatform `json:"platform"`
	// replicas is the desired number of nodes the pool should maintain. If unset, the controller default value is 0.
	// +k8s:openapi-gen=true
	// +hyperfleet:write-mode=mutable
	Replicas *int32 `json:"replicas,omitempty"`
}
