// Code generated by conversion-gen. DO NOT EDIT.

package public

// NodePool is the Schema for the nodepools API.
// It represents a set of worker nodes for a Cluster.
// The parent Cluster shares the same metadata.Namespace (cluster UUID).
type NodePool struct {
	// +required
	Spec NodePoolSpec `json:"spec"`
	// +optional
	Status NodePoolStatus `json:"status,omitzero"`
}
