// Code generated by conversion-gen. DO NOT EDIT.

package public

// Placement is the Schema for the placements API.
// It assigns a Cluster to a management cluster.
type Placement struct {
	// +required
	Spec PlacementSpec `json:"spec"`
	// +optional
	Status PlacementStatus `json:"status,omitzero"`
}
