// Code generated by conversion-gen. DO NOT EDIT.

package public

// SystemdDropin is the REST representation of SystemdDropin (visible fields only)
type SystemdDropin struct {
	Name     string `json:"name"`
	Contents string `json:"contents,omitempty"`
}
