// Code generated by conversion-gen. DO NOT EDIT.

package public

// SystemdUnit is the REST representation of SystemdUnit (visible fields only)
type SystemdUnit struct {
	Name     string          `json:"name"`
	Enabled  *bool           `json:"enabled,omitempty"`
	Contents string          `json:"contents,omitempty"`
	Dropins  []SystemdDropin `json:"dropins,omitempty"`
}
