# TODO: Remove this file after we swap to .ci-operator.yaml. 
# Podman in podman is not possible via rhel-9-release-golang-1.26-openshift-4.23 anyway, 
# so the addition we have here is unnecessary.
FROM registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.26-openshift-4.23

RUN dnf install -y podman --setopt=install_weak_deps=False && dnf clean all

