// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"

	v1alpha1 "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1"
	rest "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1/public"
	"github.com/openshift-online/rosa-hyperfleet-api/platform-api/pkg/conversion"
)

// ProjectControlPlaneUpgradePolicy converts CRD ControlPlaneUpgradePolicy to REST (visible fields only).
// Uses JSON roundtrip: marshal CRD → unmarshal into REST, so hidden fields are
// automatically dropped (REST types lack them).
func ProjectControlPlaneUpgradePolicy(crd *v1alpha1.ControlPlaneUpgradePolicy) *rest.ControlPlaneUpgradePolicy {
	if crd == nil {
		return nil
	}

	spec := projectControlPlaneUpgradePolicySpec(crd.Spec)
	status := projectControlPlaneUpgradePolicyStatus(crd.Status)
	return &rest.ControlPlaneUpgradePolicy{
		TypeMeta:   crd.TypeMeta,
		ObjectMeta: crd.ObjectMeta,
		Spec:       spec,
		Status:     status,
	}
}

func projectControlPlaneUpgradePolicySpec(crd v1alpha1.ControlPlaneUpgradePolicySpec) rest.ControlPlaneUpgradePolicySpec {
	data, _ := json.Marshal(crd)
	var out rest.ControlPlaneUpgradePolicySpec
	_ = json.Unmarshal(data, &out)
	return out
}

func projectControlPlaneUpgradePolicyStatus(crd v1alpha1.ControlPlaneUpgradePolicyStatus) rest.ControlPlaneUpgradePolicyStatus {
	data, _ := json.Marshal(crd)
	var out rest.ControlPlaneUpgradePolicyStatus
	_ = json.Unmarshal(data, &out)
	return out
}

// UnprojectControlPlaneUpgradePolicy converts REST ControlPlaneUpgradePolicySpec to CRD with service-set enrichment.
// Uses JSON roundtrip: marshal REST → unmarshal into CRD, then overlay service-set fields.
func UnprojectControlPlaneUpgradePolicy(spec *rest.ControlPlaneUpgradePolicySpec, enrichment *conversion.ServiceSetFields) *v1alpha1.ControlPlaneUpgradePolicySpec {
	if spec == nil {
		return nil
	}

	data, _ := json.Marshal(spec)
	var crdSpec v1alpha1.ControlPlaneUpgradePolicySpec
	_ = json.Unmarshal(data, &crdSpec)

	if enrichment != nil {
		ssData, _ := json.Marshal(enrichment)
		_ = json.Unmarshal(ssData, &crdSpec)
	}

	return &crdSpec
}
